<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * Extend `payment_methods.method_type` enum so every gateway the
 * PaymentService factory can build (PromptPay, bank_transfer, Stripe,
 * Omise, PayPal, LINE Pay, TrueMoney, 2C2P, manual) is representable
 * in the DB — and seed a row for Omise specifically so it shows up on
 * /admin/payments/methods.
 *
 * Prior enum: ('promptpay','bank_transfer','stripe','manual')
 *   → inserting method_type='omise' failed with 1265 "Data truncated"
 *   → admins had no way to enable Omise from the UI.
 *
 * This migration is safe to re-run logically — the `insertOrIgnore`
 * check on (method_type='omise') avoids duplicate rows, and altering
 * an enum to a superset preserves all existing data.
 */
return new class extends Migration {
    public function up(): void
    {
        // 1) Extend the enum. MySQL uses a real ENUM column, Postgres uses
        //    a varchar + CHECK constraint generated by Laravel's enum().
        $driver = DB::connection()->getDriverName();

        if ($driver === 'mysql' || $driver === 'mariadb') {
            DB::statement("
                ALTER TABLE `payment_methods`
                MODIFY COLUMN `method_type` ENUM(
                    'promptpay',
                    'bank_transfer',
                    'stripe',
                    'omise',
                    'paypal',
                    'line_pay',
                    'truemoney',
                    'two_c_two_p',
                    'manual'
                ) NOT NULL
            ");
        } elseif ($driver === 'pgsql') {
            // Drop the auto-generated CHECK constraint and replace with
            // the extended value set. Constraint name follows Laravel's
            // default: <table>_<column>_check
            DB::statement('ALTER TABLE payment_methods DROP CONSTRAINT IF EXISTS payment_methods_method_type_check');
            DB::statement("
                ALTER TABLE payment_methods
                ADD CONSTRAINT payment_methods_method_type_check
                CHECK (method_type IN (
                    'promptpay','bank_transfer','stripe','omise',
                    'paypal','line_pay','truemoney','two_c_two_p','manual'
                ))
            ");
        } elseif ($driver === 'sqlite') {
            // SQLite has no ENUM type — Laravel's `enum()` migration helper
            // emits a CHECK constraint inline with the table definition,
            // and SQLite doesn't support DROP CONSTRAINT or ALTER COLUMN
            // for check constraints. Workaround: rebuild the table.
            //
            // For test-only DBs (phpunit.xml uses sqlite::memory:) the
            // simplest correct path is to skip the CHECK rewrite entirely
            // — the seed below still works because SQLite's CHECK is
            // permissive enough that adding 'omise' falls inside the
            // text column type. Tests don't exercise the constraint.
            //
            // For a real SQLite production deploy you'd need the rebuild
            // dance: CREATE new table → INSERT SELECT → DROP old → RENAME.
            // We don't ship to SQLite production, so we skip and just
            // continue to the seed step.
            \Log::info('payment_methods enum extension: skipping on sqlite (test only)');
        }

        // 2) Seed an Omise row if one doesn't exist yet. Left disabled
        //    so the admin can flip it on only after entering keys at
        //    /admin/settings/payment-gateways.
        //
        //    Skipped on sqlite because the original table's CHECK
        //    constraint only whitelists the 4 legacy method_types;
        //    inserting 'omise' raises SQLSTATE[23000] and aborts the
        //    test migration, blocking 232 tests downstream. Production
        //    targets MySQL/Postgres which DO have the constraint
        //    rewritten by step (1) above.
        if ($driver === 'sqlite') {
            \Log::info('payment_methods omise seed: skipping on sqlite (test only)');
            return;
        }

        $exists = DB::table('payment_methods')
            ->where('method_type', 'omise')
            ->exists();

        if (! $exists) {
            $maxSort = (int) DB::table('payment_methods')->max('sort_order');
            DB::table('payment_methods')->insert([
                'method_name' => 'Omise (บัตรเครดิต / Credit Card)',
                'method_type' => 'omise',
                'is_active'   => 0,
                'sort_order'  => $maxSort + 1,
            ]);
        }
    }

    public function down(): void
    {
        // Drop the seeded row before narrowing the enum, otherwise
        // the ALTER would truncate an existing value.
        DB::table('payment_methods')->where('method_type', 'omise')->delete();
        DB::table('payment_methods')->where('method_type', 'paypal')->delete();
        DB::table('payment_methods')->where('method_type', 'line_pay')->delete();
        DB::table('payment_methods')->where('method_type', 'truemoney')->delete();
        DB::table('payment_methods')->where('method_type', 'two_c_two_p')->delete();

        DB::statement("
            ALTER TABLE `payment_methods`
            MODIFY COLUMN `method_type` ENUM(
                'promptpay',
                'bank_transfer',
                'stripe',
                'manual'
            ) NOT NULL
        ");
    }
};
